# Generated by Django 3.2.3 on 2021-05-23 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.TimeField(blank=True, default=datetime.datetime(2021, 5, 23, 21, 17, 34, 15640))),
            ],
        ),
    ]
